# Generated by Django 5.2.17 on 2026-10-01 11:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("License", "License"),
                            ("Clearance", "Clearance"),
                            ("MedicalCert", "Medical certificate"),
                            ("TrainingCert", "Training certificate"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("LESP License", "LESP License"),
                            ("NBI Clearance", "NBI Clearance"),
                            ("Police Clearance", "Police Clearance"),
                            ("Drug Test", "Drug Test"),
                            ("Neuro-Psychiatric Exam", "Neuro-Psychiatric Exam"),
                            (
                                "Basic Security Guard Course",
                                "Basic Security Guard Course",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                ("number", models.CharField(max_length=50)),
                ("issuer", models.CharField(blank=True, max_length=100)),
                ("issued", models.DateField()),
                ("expires", models.DateField()),
                ("result", models.CharField(blank=True, max_length=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["guard", "doc_type"],
                "default_permissions": ("add", "view"),
            },
        ),
        migrations.CreateModel(
            name="Clearance",
            fields=[],
            options={
                "proxy": True,
                "default_permissions": (),
                "indexes": [],
                "constraints": [],
            },
            bases=("guards.credential",),
        ),
        migrations.CreateModel(
            name="License",
            fields=[],
            options={
                "proxy": True,
                "default_permissions": (),
                "indexes": [],
                "constraints": [],
            },
            bases=("guards.credential",),
        ),
        migrations.CreateModel(
            name="MedicalCert",
            fields=[],
            options={
                "proxy": True,
                "default_permissions": (),
                "indexes": [],
                "constraints": [],
            },
            bases=("guards.credential",),
        ),
        migrations.CreateModel(
            name="TrainingCert",
            fields=[],
            options={
                "proxy": True,
                "default_permissions": (),
                "indexes": [],
                "constraints": [],
            },
            bases=("guards.credential",),
        ),
        migrations.CreateModel(
            name="CredentialVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_number", models.CharField(max_length=50)),
                ("old_issued", models.DateField()),
                ("old_expires", models.DateField()),
                ("old_result", models.CharField(blank=True, max_length=100)),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credential_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="guards.credential",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
                "abstract": False,
                "default_permissions": ("add", "view"),
            },
        ),
        migrations.CreateModel(
            name="Guard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("contact_number", models.CharField(blank=True, max_length=20)),
                ("home_address", models.CharField(blank=True, max_length=200)),
                ("employee_no", models.CharField(max_length=20, unique=True)),
                ("date_hired", models.DateField()),
                ("position", models.CharField(default="Security Guard", max_length=50)),
                ("sss_number", models.CharField(blank=True, max_length=20)),
                ("tin_number", models.CharField(blank=True, max_length=20)),
                ("philhealth_number", models.CharField(blank=True, max_length=20)),
                ("rank", models.CharField(default="Security Guard", max_length=50)),
                (
                    "guard_type",
                    models.CharField(
                        choices=[
                            ("Unarmed Security Guard", "Unarmed Security Guard"),
                            ("Armed Security Guard", "Armed Security Guard"),
                            ("Lady Security Guard", "Lady Security Guard"),
                            ("Security Officer", "Security Officer"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guard_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
                "permissions": [
                    ("view_dashboard", "Can view the dashboard"),
                    ("view_all_guards", "Can view and search all guards"),
                    ("view_own_record", "Can view own guard record"),
                    ("step_up_sensitive", "Can unlock sensitive data with a step-up"),
                    ("manage_credentials", "Can add or renew credentials"),
                ],
            },
        ),
        migrations.AddField(
            model_name="credential",
            name="guard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credentials",
                to="guards.guard",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "band",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (60, "2 months"),
                            (30, "1 month"),
                            (14, "2 weeks"),
                            (7, "1 week"),
                            (1, "1 day"),
                            (0, "Expired"),
                        ]
                    ),
                ),
                ("expiry_date", models.DateField()),
                (
                    "created_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Seen", "Seen"),
                            ("Resolved", "Resolved"),
                        ],
                        default="New",
                        max_length=10,
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="guards.credential",
                    ),
                ),
                (
                    "guard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="guards.guard",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_date", "band"],
            },
        ),
        migrations.AddConstraint(
            model_name="credential",
            constraint=models.UniqueConstraint(
                fields=("guard", "doc_type"), name="one_document_per_guard"
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("credential", "band", "expiry_date"), name="one_notice_per_band"
            ),
        ),
    ]
