# Generated by Django 5.2.17 on 2026-10-01 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("username", models.CharField(max_length=150)),
                ("role", models.CharField(max_length=50)),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "LOGIN"),
                            ("LOGOUT", "LOGOUT"),
                            ("VIEW", "VIEW"),
                            ("CREATE", "CREATE"),
                            ("UPDATE", "UPDATE"),
                            ("ASSIGN", "ASSIGN"),
                            ("STEP_UP", "STEP_UP"),
                            ("DENY", "DENY"),
                            ("TIMEOUT", "TIMEOUT"),
                            ("REPORT", "REPORT"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_type", models.CharField(blank=True, max_length=50)),
                ("target_id", models.CharField(blank=True, max_length=200)),
                (
                    "outcome",
                    models.CharField(
                        choices=[("Success", "Success"), ("Denied", "Denied")],
                        default="Success",
                        max_length=10,
                    ),
                ),
                ("sensitive", models.BooleanField(default=False)),
                ("details", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "audit entries",
                "ordering": ["-timestamp", "-id"],
                "permissions": [("view_audit_log", "Can view the audit log")],
                "abstract": False,
                "default_permissions": ("add", "view"),
            },
        ),
    ]
